services:

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: php_laravel
      MYSQL_USER: php_laravel
      MYSQL_PASSWORD: php_laravel
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
   

  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
      - vendor:/var/www/html/vendor
    ports:
      - 9000:80
    depends_on:
      - mysql
networks:
  laravel:

volumes:
  dbdata:
  vendor:
